"""Markdown report generator for git summaries."""

from datetime import datetime
from pathlib import Path


class MarkdownReportGenerator:
    """Generates Markdown reports for git summaries."""
    
    def generate(
        self,
        repo_name: str,
        days: int,
        total_commits: int,
        report_text: str,
        commits: list,
        output_path: str
    ) -> str:
        """Generate a Markdown report and save to file."""
        
        avg = round(total_commits / max(days, 1), 1)
        now = datetime.now().strftime('%Y-%m-%d %H:%M')
        
        # Build markdown content
        md_content = f"""# 📊 Git Progress Report

**Repository:** {repo_name}  
**Period:** Last {days} days  
**Generated:** {now}

---

## 📈 Statistics

| Metric | Value |
|--------|-------|
| Total Commits | {total_commits} |
| Time Period | {days} days |
| Average | {avg} commits/day |

---

## 📝 Progress Summary

{report_text}

---

## 📜 Recent Commits

"""
        # Add commits
        if commits:
            md_content += "| # | Date | Message | Author |\n"
            md_content += "|---|------|---------|--------|\n"
            
            for i, commit in enumerate(commits[:15], 1):
                if hasattr(commit, 'date'):
                    date_str = commit.date.strftime("%Y-%m-%d")
                    subject = commit.subject[:50].replace('|', '\\|')
                    author = commit.author[:20].replace('|', '\\|')
                else:
                    date_obj = commit.get('date') if isinstance(commit, dict) else None
                    date_str = date_obj.strftime("%Y-%m-%d") if date_obj else "N/A"
                    subject = str(commit.get('subject', ''))[:50].replace('|', '\\|')
                    author = str(commit.get('author', 'unknown'))[:20].replace('|', '\\|')
                
                md_content += f"| {i} | {date_str} | {subject} | {author} |\n"
            
            if len(commits) > 15:
                md_content += f"\n*... and {len(commits) - 15} more commits*\n"
        else:
            md_content += "*No commits in this period*\n"
        
        md_content += """
---

*Generated by [Git-Summarizer](https://github.com/git-summarizer)*
"""
        
        # Save file
        output_path = Path(output_path)
        if not output_path.suffix:
            output_path = output_path.with_suffix('.md')
        
        output_path.write_text(md_content, encoding='utf-8')
        return str(output_path)
